// Flat-config ESLint 9 configuration for keystone4-ts.
//
// This file replaces .eslintrc + .eslintignore. It is intentionally
// permissive during the P0 foundation phase — the goal is to get a
// modern parser running across .js, .jsx, .ts, .tsx without exploding
// on the existing legacy code. Strict rules will be ratcheted up in
// later phases (see improvements-plan.md).

import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import jsdoc from 'eslint-plugin-jsdoc';
import sonarjs from 'eslint-plugin-sonarjs';
import globals from 'globals';

export default [
	// 1. Global ignores (replaces .eslintignore).
	{
		ignores: [
			'node_modules/**',
			'dist/**',
			'coverage/**',
			'admin/bundles/**',
			'admin/public-legacy/**',
			'docs/**',
			// Third-party legacy code (bootstrap-markdown). Bundled as-is.
			'fields/types/**/lib/**',
			// Third-party React 17 peer-range forks. Runtime code is copied from
			// published packages and only package metadata is maintained locally.
			'vendor/react17-peer-forks/**',
			'**/*.bak',
			'**/*.bak.ts',
			'**/*.min.js',
			// Generated type declarations (dist/) — emitted by tsc, not source.
			'dist/**',
			'global.d.ts',
			// Nightwatch e2e tests use intentional `var self` closure patterns
			// that ESLint can't auto-fix. These tests aren't in the active test suite.
			'test/e2e/**',
			// Out-of-tree symlinked content (gitignored). Not part of this
			// project's source — should not be linted as keystone4-ts code.
			'canonical-agents/**',
			'canonical-rules/**',
			'canonical-skills/**',
			'canonical-workflows/**',
			// Per-session worktrees managed by the harness (gitignored). Their
			// contents mirror the repo from a different commit and should not
			// be re-linted in the parent's pass.
			'.claude/**',
			// Generated Playwright test reports — not source code.
			'**/playwright-report/**',
			'**/playwright-report*/**',
			'**/test-results/**',
			// Admin legacy React 15 client and field components — frozen for
			// the duration of P3/P4/P5 per .roadmap/P3-field-types/25-defer-react-fields.md.
			// Admin next typed equivalents are written under admin/client-next/. Deletion
			// is deferred to a P4-followup cutover.
			'admin/client-legacy/**',
			'fields/components/**',
			'fields/explorer/**',
			'fields/mixins/**',
			'fields/**/*Field.js',
			'fields/**/*Field.mjs',
			'fields/**/*Filter.js',
			'fields/**/*Filter.mjs',
			'fields/**/*Column.js',
			'fields/**/*Column.mjs',
			// Admin public-next — Vite-bundled output (not source). Generated by
			// `npm run build:admin-next`; changes here are ephemeral and should not
			// be linted as keystone4-ts source.
			'admin/public-next/**',
		],
	},

	// 2. Baseline recommended rules for plain JavaScript files.
	js.configs.recommended,

	// 3. Recommended rules for TypeScript files (non-type-checked tier
	//    during P0 — type-aware rules are enabled in later phases).
	...tseslint.configs.recommended,

	// 4. Repo-wide language options + globals.
	{
		linterOptions: {
			// Phase 0 turns several rules off (ESLint 10 new rules, typescript-eslint
			// 8.56+ new strictness). Existing eslint-disable comments in source files
			// for those rules now appear "unused". Suppress the warning so source files
			// don't need updating in this PR — they'll be cleaned up in Phase 3.
			reportUnusedDisableDirectives: false,
		},
		languageOptions: {
			ecmaVersion: 2022,
			sourceType: 'module',
			globals: {
				...globals.node,
				...globals.browser,
				...globals.mocha,
				_: 'readonly',
				$: 'readonly',
				jQuery: 'readonly',
				Keystone: 'readonly',
			},
			parserOptions: {
				ecmaFeatures: {
					jsx: true,
				},
			},
		},
		rules: {
			// Keep the codebase compilable while we're still mostly .js.
			// Most of these will flip back on as files convert to .ts.
			'no-unused-vars': 'off',
			'no-empty': 'off',
			'no-prototype-builtins': 'off',
			'no-redeclare': 'off',
			'no-undef': 'off',
			// Pre-existing style noise in legacy JS — re-enabled in P7 step 44.
			'no-case-declarations': 'off',
			'no-constant-condition': 'off',
			'no-useless-escape': 'off',
			'no-global-assign': 'off',
			'no-var': 'error',
			'prefer-const': 'error',
			'prefer-rest-params': 'off',
			'prefer-spread': 'off',
			// Smart mode: allows == null checks but bans other loose equality.
			// Surviving violations carry eslint-disable-line comments explaining intent.
			'eqeqeq': ['error', 'smart'],

			// Correctness-and-bug-prevention rules at warn — surface real
			// defects without breaking the build. Allow `!!x` for boolean
			// coercion; that idiom is intentional throughout the codebase.
			'no-throw-literal': 'error',
			'no-implicit-coercion': ['error', { allow: ['!!'] }],
			'no-self-compare': 'error',
			'no-unreachable-loop': 'error',
			'no-promise-executor-return': 'error',
			'no-loss-of-precision': 'error',
			'no-template-curly-in-string': 'error',

			// ESLint 10 new recommended rules — 1 violation (updateItem.mts),
			// deferred to Phase 3 via Suppressions API.
			// TODO(quality-d): re-enable after baselining via Suppressions API
			'no-useless-assignment': 'off',

			// TypeScript-specific knobs (intentionally relaxed during P0).
			// no-explicit-any: enabled globally (DoD item 14). Legacy zones
			// (admin/client-legacy, fields/components, etc.) are excluded via
			// the global ignores block above. The three JUSTIFIED `any` uses in
			// types/express.d.ts carry inline eslint-disable-line comments.
			// Test files retain the 'off' override in section 5b (separate track).
			'@typescript-eslint/no-explicit-any': 'error',
			'@typescript-eslint/no-unused-vars': 'off',
			'@typescript-eslint/no-require-imports': 'error',
			'@typescript-eslint/no-var-requires': 'error',
			'@typescript-eslint/ban-ts-comment': 'off',
			'@typescript-eslint/no-empty-object-type': 'off',
			'@typescript-eslint/no-unsafe-function-type': 'off',
			'@typescript-eslint/no-wrapper-object-types': 'off',
			'@typescript-eslint/no-this-alias': 'off',
			'@typescript-eslint/no-unused-expressions': 'off',
			// Intentional declaration merging in index.mts (Keystone class + interface).
			'@typescript-eslint/no-unsafe-declaration-merging': 'off',
		},
	},

	// 5. TypeScript strict-type-checked for .mts source files.
	//    Uses the typescript-eslint preset that requires project-aware parsing.
	//    The preset already includes every rule that was previously hand-listed
	//    here; see https://typescript-eslint.io/users/configs/#strict-type-checked
	...tseslint.configs.strictTypeChecked.map(cfg => ({
		...cfg,
		files: ['**/*.mts'],
	})),
	{
		files: ['**/*.mts'],
		languageOptions: {
			parserOptions: {
				project: './tsconfig.json',
				tsconfigRootDir: import.meta.dirname,
			},
		},
		rules: {
			// Project-specific overrides on top of strictTypeChecked:

			// Template expressions allow number/boolean/nullish/regexp coercion.
			'@typescript-eslint/restrict-template-expressions': ['error', {
				allowNumber: true, allowBoolean: true, allowNullish: true, allowRegExp: true,
			}],
			// Restrict-plus-operands: be lenient — the codebase uses string+number freely.
			'@typescript-eslint/restrict-plus-operands': ['error', {
				allowAny: true, allowBoolean: true, allowNullish: true,
				allowNumberAndString: true, allowRegExp: true,
			}],
			// Misused promises: allow async fn as event handler attributes (e.g. onClick).
			'@typescript-eslint/no-misused-promises': ['error', { checksVoidReturn: { attributes: false } }],
			// Non-null assertions: keep as error.
			'@typescript-eslint/no-non-null-assertion': 'error',
			// Shadowing: already enforced; keep.
			'@typescript-eslint/no-shadow': 'error',
			// Unused vars: already enforced with underscore-ignore pattern; keep.
			'@typescript-eslint/no-unused-vars': ['error', {
				args: 'after-used',
				argsIgnorePattern: '^_',
				varsIgnorePattern: '^_',
				caughtErrorsIgnorePattern: '^_',
				destructuredArrayIgnorePattern: '^_',
			}],
			// Nullish coalescing: ignorePrimitives option changed in typescript-eslint
			// 8.56+ and now fires on string || and ||= patterns we use intentionally.
			// TODO(quality-d): re-enable after baselining via Suppressions API
			'@typescript-eslint/prefer-nullish-coalescing': 'off',
			// Consistent type imports: lib/list.mts uses ReturnType<typeof import('mongoose').model>
			// which is an inline import() type in a generic position. Turn off for .mts;
			// .ts/.tsx files still enforce via section 5b (e2e exceptions via section 8).
			// TODO(quality-d): re-enable after baselining via Suppressions API
			'@typescript-eslint/consistent-type-imports': 'off',
			// Deprecated: downgrade to warn (not all usages can be fixed in this pass).
			'@typescript-eslint/no-deprecated': 'warn',
			// Allow void-returning promises to be used as statement expressions.
			'@typescript-eslint/no-floating-promises': 'error',
			// no-invalid-void-type: allow `this: void` parameter in function signatures.
			'@typescript-eslint/no-invalid-void-type': ['error', { allowAsThisParameter: true }],
			// prefer-promise-reject-errors: allow rejecting with non-Error values in legacy code.
			'@typescript-eslint/prefer-promise-reject-errors': ['error', { allowThrowingAny: true, allowThrowingUnknown: true }],
			// no-confusing-void-expression: Express/callback middleware uses `return res.send()`
			// and `return next()` as a standard bail-early pattern; keep it off.
			'@typescript-eslint/no-confusing-void-expression': 'off',
			// Enabled for .mts source files — all violations resolved in iteration 51.
			// Test .mts files remain excluded via the test-file override in section 5b.
			// '@typescript-eslint/no-explicit-any' is now 'error' (inherited from strictTypeChecked).
			'@typescript-eslint/ban-ts-comment': 'off',
			'@typescript-eslint/no-empty-object-type': 'off',
			'@typescript-eslint/no-unsafe-function-type': 'off',
			'@typescript-eslint/no-wrapper-object-types': 'off',
			'@typescript-eslint/no-this-alias': 'off',
			'@typescript-eslint/no-unused-expressions': 'off',
			'@typescript-eslint/no-unsafe-declaration-merging': 'off',
			// Overly strict rules that don't apply to this codebase's patterns:
			// typescript-eslint 8.56+ stricter no-unnecessary-type-assertion — 8 violations
			// in RelationshipType.mts; defer to Phase 3.
			// TODO(quality-d): re-enable after baselining via Suppressions API
			'@typescript-eslint/no-unnecessary-type-assertion': 'off',
			'@typescript-eslint/no-unsafe-argument': 'error',
			'@typescript-eslint/no-unsafe-assignment': 'error',
			'@typescript-eslint/no-unsafe-call': 'error',
			'@typescript-eslint/no-unsafe-member-access': 'error',
			'@typescript-eslint/no-unsafe-return': 'error',
			// prefer-rest-params and prefer-spread were globally disabled in section 4;
			// the strictTypeChecked preset re-enables them — keep them off for .mts too.
			'prefer-rest-params': 'off',
			'prefer-spread': 'off',
		},
	},

	// 5b. Tighter rules for new TypeScript files only.
	{
		// Note: .mts files are excluded here — section 5 above turns
		// consistent-type-imports off for .mts (lib/list.mts inline import() type).
		files: ['**/*.ts', '**/*.tsx'],
		rules: {
			'@typescript-eslint/consistent-type-imports': 'error',
		},
	},

	// 5c. Deliberate CommonJS compatibility shims.
	{
		files: ['**/*.cjs'],
		languageOptions: {
			sourceType: 'commonjs',
		},
		rules: {
			'@typescript-eslint/no-require-imports': 'off',
			'@typescript-eslint/no-var-requires': 'off',
		},
	},

	// 5b. Test files use chai-style property assertions (e.g.
	//     `expect(x).to.be.true`) which look like no-op expressions to
	//     the no-unused-expressions rule. Disable for test/spec files.
	//     sonarjs/assertions-in-tests only recognises Jest/jasmine assertion
	//     APIs; Chai expect/.to.* and Node assert.* are false-positives here.
	//
	//     no-non-null-assertion: field test files use `List.fields.fieldName!.method()`
	//     because noUncheckedIndexedAccess makes indexed dict access nullable, but
	//     tests know the field is present (they just registered it). The `!` is the
	//     correct idiomatic pattern here; runtime null checks in every test call
	//     would be verbose noise without safety benefit.
	{
		files: ['test/**/*.{js,mjs,mts,ts}', '**/*.test.{js,mjs,mts,ts}', 'fields/**/test/**/*.{js,mjs,mts}', 'admin/**/test*/**/*.{js,mjs,mts}', 'admin/**/tests/**/*.{js,mjs,mts}'],
		rules: {
			'@typescript-eslint/no-unused-expressions': 'off',
			'@typescript-eslint/no-unsafe-argument': 'off',
			'@typescript-eslint/no-unsafe-assignment': 'off',
			'@typescript-eslint/no-unsafe-call': 'off',
			'@typescript-eslint/no-unsafe-member-access': 'off',
			'@typescript-eslint/no-unsafe-return': 'off',
			'no-unused-expressions': 'off',
			'sonarjs/assertions-in-tests': 'off',
			'@typescript-eslint/no-non-null-assertion': 'off',
		},
	},

	// 5a. SonarJS — code-quality and bug-detection rules for migrated files.
	//     Scoped to .mjs, .ts, .tsx to avoid noise on unmigrated CommonJS files.
	//     Several "noise" rules are demoted to warnings during P0/P1 — they
	//     re-enable in P7 step 44 (final lint sweep).
	{
		files: ['**/*.mjs', '**/*.mts', '**/*.ts', '**/*.tsx'],
		plugins: { sonarjs },
		rules: {
			...sonarjs.configs.recommended.rules,
			// All sonarjs/* findings on this 10-year-old codebase are about
			// patterns we either intentionally keep (TODO/FIXME markers,
			// http: URLs in test fixtures and dev HTTP listeners, sha1 for
			// CSRF token signing) or are scheduled to clean up wholesale
			// during P4 (admin/client-legacy rewrite) or P7 step 44 (final lint
			// sweep). Demoting all to off here so lint output isn't noise;
			// the strict-type-checked preset re-enables them in P7 step 44.
			'sonarjs/cognitive-complexity': 'off',
			'sonarjs/no-extra-arguments': 'off',
			'sonarjs/no-ignored-exceptions': 'off',
			'sonarjs/no-clear-text-protocols': 'off',
			'sonarjs/todo-tag': 'off',
			'sonarjs/fixme-tag': 'off',
			'sonarjs/hashing': 'off',
			'sonarjs/no-nested-functions': 'off',
			'sonarjs/anchor-precedence': 'off',
			'sonarjs/no-code-after-done': 'off',
			'sonarjs/no-incomplete-assertions': 'off',
			'sonarjs/no-unused-vars': 'off',
			'sonarjs/no-identical-functions': 'off',
			'sonarjs/unused-import': 'off',
			'sonarjs/no-commented-code': 'off',
			'sonarjs/no-skipped-tests': 'off',
			'sonarjs/slow-regex': 'off',
			'sonarjs/no-nested-conditional': 'off',
			'sonarjs/pseudo-random': 'off',
			'sonarjs/no-os-command-from-path': 'off',
			'sonarjs/no-nested-assignment': 'off',
			'sonarjs/no-identical-expressions': 'off',
			'sonarjs/no-gratuitous-expressions': 'off',
			'sonarjs/no-globals-shadowing': 'off',
			'sonarjs/no-empty-test-file': 'off',
			'sonarjs/no-duplicated-branches': 'off',
			// SonarJS doesn't detect chai-style assertions
			// (`expect(x).to.be.true`) and reports every chai-using
			// `it(...)` as a no-assertion test. False positive.
			'sonarjs/assertions-in-tests': 'off',
			// `void expr;` is used intentionally in stub .mts files to satisfy
			// TypeScript's unused-parameter check without removing the param.
			'sonarjs/void-use': 'off',
			// Test fixtures intentionally write to system temp dirs.
			'sonarjs/publicly-writable-directories': 'off',
			// Chai-based tests catch raw Error objects; sonarjs expects typed catches.
			'sonarjs/test-check-exception': 'off',
			// New e2e heavy test file populates consoleErrors for future assertion;
			// defer to Phase 3 cleanup.
			// TODO(quality-d): re-enable after baselining via Suppressions API
			'sonarjs/no-unused-collection': 'off',
		},
	},

	// 6. JSDoc structural-correctness enforcement for first-party source files
	//    (.js, .jsx, .mjs, .cjs, .mts). We focus on rules that catch JSDoc
	//    that is wrong (mismatched param names, invalid tag names, undefined
	//    types) rather than rules that demand missing documentation. The
	//    "require-*" family stays off here so we don't drown in stylistic
	//    warnings on legacy untyped code; they flip on selectively in later
	//    phases.
	{
		files: ['**/*.js', '**/*.jsx', '**/*.mjs', '**/*.cjs', '**/*.mts'],
		...jsdoc.configs['flat/recommended'],
		rules: {
			...jsdoc.configs['flat/recommended'].rules,
			// Disabled: require-* rules are too noisy on legacy untyped source.
			// They flip on per-file as code converts to TypeScript.
			'jsdoc/require-jsdoc': 'off',
			'jsdoc/require-description': 'off',
			'jsdoc/require-returns': 'off',
			'jsdoc/require-returns-description': 'off',
			'jsdoc/require-param': 'off',
			'jsdoc/require-param-description': 'off',
			'jsdoc/require-param-type': 'off',
			'jsdoc/require-returns-type': 'off',
			'jsdoc/require-property-description': 'off',
			'jsdoc/tag-lines': 'off',
			'jsdoc/no-defaults': 'off',
			'jsdoc/reject-any-type': 'off',
			// Enabled at warn: structural-correctness rules. JSDoc that is
			// wrong, contradicts the code, or references nonexistent types
			// is a real defect — not a stylistic gap.
			'jsdoc/check-alignment': 'error',
			'jsdoc/check-param-names': 'error',
			'jsdoc/check-tag-names': 'error',
			'jsdoc/check-types': 'error',
			'jsdoc/empty-tags': 'error',
			'jsdoc/multiline-blocks': 'error',
			'jsdoc/no-multi-asterisks': 'error',
			// Disabled: {@link FunctionName} in .mts JSDoc triggers false positives
			// (jsdoc-plugin doesn't resolve function names as types).
			'jsdoc/no-undefined-types': 'off',
			'jsdoc/require-property': 'error',
			'jsdoc/require-property-name': 'error',
			'jsdoc/require-property-type': 'error',
			'jsdoc/require-returns-check': 'error',
			'jsdoc/valid-types': 'error',
			'jsdoc/reject-function-type': 'error',
		},
	},

	// 7. JSDoc enforcement for TypeScript files.
	//    Uses the TypeScript-aware preset which skips @param/@returns type
	//    annotations (TypeScript already captures those) and focuses on
	//    description quality and structural correctness.
	//    Ambient `.d.ts` declarations are excluded — types ARE the docs.
	{
		files: ['**/*.ts', '**/*.tsx'],
		ignores: ['**/*.d.ts'],
		...jsdoc.configs['flat/recommended-typescript'],
		rules: {
			...jsdoc.configs['flat/recommended-typescript'].rules,
			'jsdoc/require-jsdoc': [
				'error',
				{
					publicOnly: true,
					require: {
						FunctionDeclaration: true,
						MethodDefinition: true,
						ClassDeclaration: true,
						ArrowFunctionExpression: false,
						FunctionExpression: false,
					},
				},
			],
			'jsdoc/require-description': 'error',
			'jsdoc/check-param-names': 'error',
			'jsdoc/require-returns': 'error',
			// Don't duplicate @param types — TypeScript owns the types.
			'jsdoc/require-param-type': 'off',
			'jsdoc/require-returns-type': 'off',
		},
	},

	// Phase 3 — Strict JSDoc on public server-side APIs.
	// Existing violations grandfathered via eslint-suppressions.json — see Phase 3 of quality-d rollout.
	//
	// Scoped to .mts source files in lib/, server/, admin/server/, fields/types/.
	// Test subdirectories are excluded so test helpers don't need JSDoc.
	{
		files: [
			'lib/**/*.mts',
			'server/**/*.mts',
			'admin/server/**/*.mts',
			'fields/types/**/*.mts',
		],
		ignores: [
			'lib/**/test/**/*.mts',
			'lib/**/*.test.mts',
			'lib/**/*.spec.mts',
			'server/**/test/**/*.mts',
			'server/**/*.test.mts',
			'server/**/*.spec.mts',
			'admin/server/**/test/**/*.mts',
			'admin/server/**/*.test.mts',
			'admin/server/**/*.spec.mts',
			'fields/types/**/test/**/*.mts',
			'fields/types/**/*.test.mts',
			'fields/types/**/*.spec.mts',
		],
		rules: {
			'jsdoc/require-jsdoc': [
				'error',
				{
					publicOnly: true,
					require: {
						FunctionDeclaration: true,
						ClassDeclaration: true,
						MethodDefinition: true,
						ArrowFunctionExpression: false,
						FunctionExpression: false,
					},
					contexts: ['TSInterfaceDeclaration', 'TSTypeAliasDeclaration'],
				},
			],
			'jsdoc/require-param': 'error',
			'jsdoc/require-param-description': 'error',
			'jsdoc/require-returns': 'error',
			'jsdoc/require-returns-description': 'error',
			'jsdoc/require-description': 'error',
		},
	},

	// 8. E2E and test helper TypeScript files — relaxed JSDoc + type-import
	//    rules. These files are test infrastructure, not public API. The
	//    jsdoc require-* rules and consistent-type-imports enforcements added
	//    in sections 5b/7 are too strict for Playwright test helpers that use
	//    inline import() type annotations.
	//    TODO(quality-d): re-enable after baselining via Suppressions API
	{
		files: [
			'e2e-ui/**/*.ts',
			'e2e-api/**/*.ts',
			'test/**/*.ts',
			'test/**/*.mts',
		],
		rules: {
			// Playwright test helpers frequently use inline `import()` type
			// annotations in function parameters — 15 violations surfaced
			// after typescript-eslint 8.56+ bump.
			'@typescript-eslint/consistent-type-imports': 'off',
			// Test helper functions don't require JSDoc documentation.
			'jsdoc/require-jsdoc': 'off',
			'jsdoc/require-returns': 'off',
			'jsdoc/require-param': 'off',
			'jsdoc/require-description': 'off',
		},
	},

	// 9. Admin next client — active React 18 source. Lint it for correctness
	// and zero warnings, but do not require public-API JSDoc on internal
	// components, route render functions, and field widgets.
	{
		files: ['admin/client-next/**/*.{ts,tsx}'],
		rules: {
			'@typescript-eslint/consistent-type-imports': 'off',
			'jsdoc/check-tag-names': 'off',
			'jsdoc/require-description': 'off',
			'jsdoc/require-jsdoc': 'off',
			'jsdoc/require-param': 'off',
			'jsdoc/require-returns': 'off',
			'jsdoc/tag-lines': 'off',
			'sonarjs/no-nested-template-literals': 'off',
		},
	},
];
