/*
This file exports the common packages required by the Admin UI.

It is used by build.js to to generate public/js/packages.js, and the packages
below are excluded from the browserify builds generated by
admin/server/middleware/browserify.js
*/

export default [
	'glamor',
	'classnames',
	'lodash',
	'marked',
	'moment',
	'numeral',
	'qs',
	'react-color',
	'react-day-picker',
	'react-dnd-html5-backend',
	'react-dnd',
	'react-dom',
	'react-images',
	'react-redux',
	'react-router-redux',
	'react-router',
	'react-select',
	'react-transition-group/CSSTransitionGroup',
	'react',
	'redux-saga',
	'redux-thunk',
	'redux',
	'xhr',
];
