export const LOAD_COUNTS = 'app/Home/LOAD_COUNTS';
export const COUNTS_LOADING_SUCCESS = 'app/Home/COUNTS_LOADING_SUCCESS';
export const COUNTS_LOADING_ERROR = 'app/Home/COUNTS_LOADING_ERROR';

export default { LOAD_COUNTS, COUNTS_LOADING_SUCCESS, COUNTS_LOADING_ERROR };
